export interface BlogPost {
  slug: string;
  title: string;
  category: string;
  excerpt: string;
  image: string;
  date: string;
  body: string[];
  inlineImages?: { afterParagraph: number; src: string; alt: string }[];
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "35-years-retrospective",
    title: "35 Years of Fearless Theatre: A Retrospective",
    category: "Feature",
    excerpt: "From Master Phoolmani in 1999 to Clean Bold in 2025, a look back at the productions, people, and moments that defined Ideas Unlimited.",
    image: "/images/placeholder-production.svg",
    date: "2024-01-10",
    body: [
      "When Manoj Shah staged Master Phoolmani at the Prithvi Festival in 1999, he had no idea it would become the longest-running production in our repertoire. Sixteen years it ran, from 1999 to 2015. That kind of longevity in Indian theatre is almost unheard of.",
      "But longevity was never the goal. The goal was always the same: make theatre that tells the truth. Make theatre that refuses to look away.",
      "In the early years, we were prolific and experimental. Between 1999 and 2005, we staged nearly forty productions \u2014 monologues, dramatised readings, full-length plays, poetry collages. We performed wherever we could: Prithvi Theatre, NCPA, Forbes Gujarati Sabha, book launches, literary festivals.",
      "The mid-2000s brought a shift toward what would become our signature: biographical plays. Mareez in 2004. Apurva Avsar in 2007. These weren\u2019t conventional biopics. They were explorations of ideas through the lens of extraordinary lives.",
      "Then came Karl Marx In Kalbadevi in 2012, and everything changed. The idea of Karl Marx visiting a chaotic Mumbai neighbourhood was so delightfully absurd, so perfectly Indian, that it became our calling card. It\u2019s been performed in Hindi, Hinglish, and English, at colleges, corporates, and international conferences.",
      "The last decade has seen us push into new territory: Dr. Anandibai performed in three languages, Adbhut exploring mental health, Mr. Apple reimagining Steve Jobs through an Indian lens. Each production is different, but the DNA is the same \u2014 strong writing, minimal staging, maximum truth.",
      "As we look at the 99 productions behind us and the unknown number ahead, one thing is clear: the hunger hasn\u2019t diminished. If anything, it\u2019s sharper than ever.",
    ],
  },
  {
    slug: "why-hindi-theatre-matters",
    title: "Why Hindi Theatre Matters in 2024",
    category: "Opinion",
    excerpt: "In a world dominated by screens, live Hindi theatre remains one of the most powerful ways to hold a mirror to Indian society.",
    image: "/images/placeholder-production.svg",
    date: "2024-03-22",
    body: [
      "There\u2019s a question that comes up at every panel discussion, every theatre festival, every funding meeting: is theatre still relevant?",
      "The question itself reveals a misunderstanding. Theatre isn\u2019t competing with Netflix or Instagram or YouTube. Theatre is doing something none of those platforms can do: putting human beings in the same room, breathing the same air, sharing the same silence.",
      "Hindi theatre, specifically, occupies a unique position in Indian culture. It\u2019s the language of Bollywood, yes, but on stage it becomes something else entirely. Freed from the constraints of commercial cinema, Hindi theatre can be experimental, uncomfortable, political, poetic \u2014 all the things that mainstream entertainment struggles to be.",
      "At Ideas Unlimited, we\u2019ve always believed that language is not a barrier but a bridge. We produce in Hindi, Gujarati, and English not because we\u2019re trying to cover the market, but because each language opens a different door into the human experience.",
      "Consider Popcorn with Parsai, our Hindi adaptation of Harishankar Parsai\u2019s satirical work. Parsai\u2019s Hindi is sharp, colloquial, deeply rooted in North Indian middle-class life. There is no way to translate it into English without losing everything that makes it sing. The play works because the language IS the performance.",
      "Theatre matters because it\u2019s the last truly democratic art form. You don\u2019t need Wi-Fi. You don\u2019t need a subscription. You just need a room, a performer, and an audience willing to listen.",
      "That will always matter.",
    ],
  },
  {
    slug: "travelling-theatre-siachen",
    title: "Performing at Siachen: Theatre at 20,000 Feet",
    category: "Behind the Scenes",
    excerpt: "When the Indian Military invited us to perform at the Siachen base camp, we said yes without hesitation. Here\u2019s what happened next.",
    image: "/images/productions/mohan-no-masalo/DSC_0378.JPG",
    date: "2023-08-05",
    body: [
      "The call came from the Indian Army\u2019s cultural division. Would Ideas Unlimited be willing to perform for troops stationed at Siachen \u2014 the highest battlefield in the world?",
      "We didn\u2019t hesitate. Our Travelling Theatre philosophy has always been about reaching audiences wherever they are. A restaurant in Bandra? Sure. A jail in Ahmedabad? Absolutely. The Siachen base camp at 20,000 feet? Let\u2019s go.",
      "The logistics were unlike anything we\u2019d faced. At that altitude, you can\u2019t take deep breaths, let alone project your voice across a room. The cold is not the kind you can layer against \u2014 it\u2019s the kind that gets into your bones and stays.",
      "We performed Mohan No Masalo \u2014 our play on young Gandhi. It\u2019s a one-person show, which made it practical for the conditions. But more than that, there was something deeply appropriate about performing a play about courage and conviction for soldiers who embody those qualities every day.",
      "The auditorium was a military hall with metal chairs and concrete walls. The acoustics were terrible. The audience \u2014 about a hundred soldiers \u2014 sat in full winter gear. None of that mattered.",
      "When the performance ended, there was a moment of absolute stillness. Then applause that shook the walls. Several soldiers came up afterward and said they hadn\u2019t seen a live performance in years. One young jawan said it was the first play he\u2019d ever seen.",
      "We\u2019ve performed at Prithvi Theatre, at NCPA, at international festivals. But that performance at Siachen is the one we talk about most. Because it proved something we\u2019ve always believed: theatre doesn\u2019t need a fancy venue. It just needs people.",
    ],
  },
  {
    slug: "karl-marx-kalbadevi-story",
    title: "How Karl Marx Ended Up in Kalbadevi",
    category: "Director\u2019s Note",
    excerpt: "The story behind one of our most popular plays \u2014 imagining what would happen if Karl Marx visited a chaotic Mumbai neighbourhood. Twelve years and counting.",
    image: "/images/productions/karl-marx-in-kalbadevi/Satchit Puranik in NCPA.jpg",
    date: "2023-05-18",
    body: [
      "The idea was Uttam Gada\u2019s, and it was brilliantly simple: what if Karl Marx \u2014 the philosopher of class struggle \u2014 visited Kalbadevi, one of Mumbai\u2019s most chaotic, commercial, quintessentially capitalist neighbourhoods? Where Kutchi shopkeepers employ armies of relatives and gaonwalas. Where capitalism is pursued and practised without apology. Where a rich meal at the famous Bhagat Tarachand is fraught with some guilt, and a pied-\u00e0-terre in a crowded chawl reminds Marx of his early days of poverty, struggle, and the writing of Das Kapital.",
      "When Uttam first pitched it, I laughed. Then I thought about it for a week. Then I called him back and said, \u201CThis is the most Indian idea anyone has ever had about a German philosopher.\u201D",
      "The play works because it\u2019s not really about Marx. It\u2019s about Mumbai. It\u2019s about how India digests and transforms every idea that comes its way \u2014 communism, capitalism, spirituality, modernity \u2014 into something uniquely, irreducibly Indian. Marx learns Gujarati because of his admiration for Mahatma Gandhi, but when he goes to Mani Bhavan, he finds the gates shut. He rants about billionaires launching rockets, then does the Gangnam Style dance. He reviews a Gujarati thali. He takes on the Ambanis. He questions everything from capitalism to chutney to Gandhi\u2019s charkha.",
      "We first staged it at the NCPA Vasant Gujarati Natya Utsav in 2013. The response was immediate. People who had never voluntarily attended a play about political philosophy were quoting lines at dinner parties. Deepa Gahlot wrote in Time Out Mumbai that the play was \u2018enough to provoke the audience to go back thinking, this Karlbhai was one clever dude, eh?\u2019 Keyur Seta called it \u2018a fine example of revolution through entertainment\u2019 that \u2018deserves to be translated to other languages.\u2019 Deepa Punjani at Mumbai Theatre Guide called the title \u2018enticing, full of prospects\u2019 and dared us to be \u2018more risky and provoking.\u2019 We took that dare.",
      "Since then, Karl Marx In Kalbadevi has had more lives than we ever imagined. We\u2019ve done it in Gujarati, Hindi, and Hinglish. At Wilson College for the 150th anniversary of Das Kapital. At the Aligarh Muslim University international theatre conference. At JAINA conventions in the United States. It has been running for twelve years and shows no sign of stopping.",
      "The play has been performed by Satchit Puranik, who brings a manic energy to Marx that makes the philosopher feel less like a historical figure and more like your most opinionated uncle at a family wedding. He looks the part \u2014 wild hair, thick beard, a tilak on his forehead that Marx himself would have found philosophically confusing. He holds the stage alone for ninety minutes with nothing but a desk, a chair, some books, a water bottle, and a suitcase. The audience never looks away.",
      "Marx\u2019s views on capitalism are in fact being studied in new light after the 2008 financial crisis. He may have been completely wrong about communism \u2014 we have history to prove that \u2014 but his readings of capitalism have never seemed more urgent. The play does not pretend to offer a complex analysis of Marxist philosophy. What it offers is something more valuable: it takes a figure consigned to the dustheap of history and makes him feel like someone you\u2019d want to argue with over chai.",
      "People ask me why this play works so well. I think it\u2019s because it does what the best theatre does: it takes something you think you know and makes you see it completely differently. It comforts the disturbed. And disturbs the comfortable.",
    ],
    inlineImages: [
      { afterParagraph: 2, src: "/images/productions/karl-marx-in-kalbadevi/show at prithvi.jpg", alt: "Satchit Puranik as Karl Marx at Prithvi Theatre \u2014 feet up, holding court" },
      { afterParagraph: 4, src: "/images/productions/karl-marx-in-kalbadevi/Karl Marx 2.jpg", alt: "Marx contemplates Das Kapital in Kalbadevi" },
      { afterParagraph: 6, src: "/images/productions/karl-marx-in-kalbadevi/Karl Marx.jpg", alt: "Satchit Puranik \u2014 the manic energy of Karl Marx In Kalbadevi" },
    ],
  },
  {
    slug: "anandibai-three-languages",
    title: "Dr. Anandibai in Three Languages",
    category: "Behind the Scenes",
    excerpt: "Staging the same play in Gujarati, Hindi, and Marathi taught us more about India\u2019s linguistic soul than any textbook ever could.",
    image: "/images/placeholder-production.svg",
    date: "2023-02-14",
    body: [
      "Dr. Anandibai Joshi was India\u2019s first female doctor. She was Marathi by birth, educated in an English-speaking world, and her story resonates across every linguistic community in India. So when Gita Manek wrote the play for us, we knew from the start that one language wouldn\u2019t be enough.",
      "The Gujarati version came first, in 2017. Manasi Joshi performed it with a ferocity that took everyone by surprise. The play is structured as a social media interaction \u2014 Like, Comment, Share \u2014 which gives it a contemporary edge that makes a 19th-century story feel urgently modern.",
      "The Hindi version followed in 2018, for Bhavan\u2019s College. Here\u2019s what fascinated us: the same lines, translated into Hindi, carried different emotional weight. Hindi\u2019s Urdu-inflected vocabulary gave certain scenes a poetic quality that the Gujarati version expressed through directness.",
      "Then came the Marathi version for the Damu Kenkre Festival. This was the most personal \u2014 Anandibai was Marathi, and performing her story in her own language felt like bringing her home. The audience response was visceral.",
      "What we learned from this experiment is something we\u2019ve always intuited but never proved so clearly: language isn\u2019t just a vehicle for content. Language IS content. The same story told in three languages becomes three different stories \u2014 each true, each complete, each revealing something the others cannot.",
      "This is why Ideas Unlimited will always be a multilingual company. Not because it\u2019s good business \u2014 it\u2019s actually harder and more expensive \u2014 but because India itself is multilingual, and any theatre that claims to reflect India must speak in more than one tongue.",
    ],
  },
  {
    slug: "mareez-ghalib-of-gujarat",
    title: "Mareez: The Poet Who Sold His Ghazals for Five Rupees and Became Immortal",
    category: "Heritage",
    excerpt: "Abbas Abdul Ali Vasi dropped out of school in the second grade. He died on a Mumbai street at sixty-six. In between, he wrote the poetry that made him the Ghalib of Gujarat. The play has been running for twenty years.",
    image: "/images/productions/mareez/Copy of Mareez (5).JPG",
    date: "2024-11-16",
    body: [
      "On 16 November 2004, a play opened at Prithvi Theatre in Mumbai. Twenty years later, it is still running. Two hundred performances. The same actor in the lead role. The same director. The same six paintings by Ghulam Mohammed Sheikh serving as the set. The same music by Uday Mazumdar. The play is Mareez, and it is the longest-running Gujarati play in existence.",
      "Abbas Abdul Ali Vasi was born in the Pathanwada area of Surat in 1917, the third of eleven children in a Dawoodi Bohra family. His father taught at a Madrasah. His mother died of tuberculosis when he was young. He dropped out of school after the second grade. At fourteen, inspired by his elder sister Rukhaiya\u2019s recitations of the Urdu poets Anis and Dabeer, he composed his first poem. His mentor Ameen Azad gave him the pen name Mareez \u2014 literally, \u2018a sick man.\u2019 It would prove more accurate than anyone intended.",
      "By his twenties, Mareez was frequenting the Zhapa Bazar in Surat, where ghazal enthusiasts gathered. He moved to Mumbai in 1932, worked in a rubber shoe factory, drifted through journalism, and began selling his ghazals to wealthy patrons who published them under their own names. Five rupees a ghazal. The tea-house audiences of Mumbai memorised his verses. The literary establishment ignored him. He drank. He loved a woman who would not love him back \u2014 a cousin whose family rejected his proposal because of his drinking and smoking. He married Sona, who stood by him. He contracted tuberculosis. He was, in every sense of the word, Mareez.",
      "The play, adapted by Vinit Shukla from Raeesh Maniar\u2019s biography Mareez: Astitva Ane Vyaktitva, does not tell this story in sequence. It moves the way a ghazal moves \u2014 through feeling, not chronology. Hallucinations interrupt memories. Poetry dissolves into dialogue. A child-Buddha appears offering Mareez middle-class salvation. Time collapses. The structure owes as much to Vincent van Gogh\u2019s letters Dear Theo and Charles Bukowski\u2019s Barfly as it does to any Gujarati dramatic tradition.",
      "Dharmendra Gohil has played Mareez since opening night \u2014 twenty years in the same role. The critic Utpal Bhayani wrote that \u2018Mareez was in his veins.\u2019 Deepa Punjani at Mumbai Theatre Guide called his performance \u2018simple yet effective and evocative,\u2019 ranging from the charismatic young poet to the broken alcoholic. The transformation happens not through makeup or costume changes but through the body \u2014 the way Gohil carries himself shifts from expansive and burning to hunched and hollowed as the play progresses.",
      "Kumkum Das plays Sona with a stillness that counterbalances Gohil\u2019s restless energy. Where he spirals and burns, she endures. Her silence speaks as loudly as his poetry. Dayashankar Pandey appears as Saadat Hasan Manto \u2014 another tormented writer, another man destroyed by the gap between his talent and his circumstances. Aishwarya Mehta plays Rabab, the girlfriend. Jay Upadhyay, Darshan Pandya, Hussaini Dawavala, and Pradeep Vengurlekar fill out the ensemble of fifteen actors.",
      "The visual design is by Ghulam Mohammed Sheikh \u2014 the Padma Bhushan-awarded painter from Vadodara whose work hangs in the Victoria and Albert Museum and the National Gallery of Modern Art. His six paintings for Mareez are not decoration. They are the world of the play. The actors move within and against depictions of the streets and mehfils of Surat and Mumbai. This was the second collaboration between Shah and a major painter, after Bhupen Khakhar\u2019s backdrops for Master Phoolmani.",
      "Mareez the poet died on 19 October 1983. He was hit by an auto-rickshaw on a Mumbai street on 13 October and died six days later of a heart attack during surgery. He was sixty-six. His first collection of ghazals, Aagman, had been published only eight years earlier, in 1975. His complete works were not published until 2012. He received the Premanand Suvarna Chandrak \u2014 one of the most prestigious awards in Gujarati literature \u2014 posthumously, in 1984.",
      "The play\u2019s subtitle is \u2018Sufi on the Rock Since 2004.\u2019 It is a perfect description. Mareez is not comfortable theatre. It does not redeem its subject. It does not sentimentalise addiction or romanticise poverty. It shows a man who was brilliant, self-destructive, exploited, and fearless \u2014 a man who wrote poetry of such intensity that people memorised it in tea houses, and yet who could not feed himself. The play asks no one to pity him. It asks them to listen. Two hundred times, audiences have listened. They keep coming back.",
    ],
    inlineImages: [
      { afterParagraph: 2, src: "/images/productions/mareez/Copy of Mareez (3).JPG", alt: "Dharmendra Gohil as the young Mareez \u2014 the poet in his element" },
      { afterParagraph: 5, src: "/images/productions/mareez/Copy of Mareez (1).JPG", alt: "The ensemble of Mareez against Ghulam Mohammed Sheikh\u2019s painted backdrop" },
      { afterParagraph: 7, src: "/images/productions/mareez/Copy of IMG_0114.JPG", alt: "Dharmendra Gohil as Mareez \u2014 the drinking scene, twenty years in the role" },
    ],
  },
  {
    slug: "kaagdo-happiness-decoded",
    title: "Kaagdo: What If Happiness Is Not the Problem but the Answer?",
    category: "Director\u2019s Note",
    excerpt: "A man is taken to court for being happy. His crime: contentment in a world that demands ambition. Ideas Unlimited\u2019s Kaagdo asks the question nobody wants answered.",
    image: "/images/productions/kaagdo/DSC02998.JPG",
    date: "2019-07-15",
    body: [
      "There is a Gujarati folk tale called Anandi Kaagdo \u2014 The Happy Crow. A crow is found at fault by the king, who devises one punishment after another. The crow sings through every one of them. It enjoys the cage. It enjoys the hunger. It enjoys the cold. The king grows furious. How do you punish someone who simply refuses to be unhappy?",
      "Manoj Shah turned this question into a play. Kaagdo, written by Geeta Manek, premiered at the Prithvi Theatre Festival in June 2019. It runs ninety minutes. It has two actors, a platform, a chair, and a backdrop of floating smiley-face balls. It is, beneath its gentle comic surface, one of the most unsettling things Ideas Unlimited has ever staged.",
      "The premise is deceptively simple. A man \u2014 a modest government worker whose wife has died, whose only daughter lives abroad, who owns nothing of material value \u2014 is inexplicably, unshakeably happy. This is considered suspicious. In a world that measures worth through acquisition, productivity, and visible striving, a man who simply sits and smiles is either hiding something or broken. He is taken to court. A lawyer is brought in to interrogate him, to find the secret formula, to crack open his contentment and expose whatever must be rotting inside.",
      "Jay Upadhyay plays the happy man \u2014 barefoot, in a striped sweater, sitting on his platform with the calm of someone who has nowhere else to be. Unnati Gala plays his daughter, sharp-suited and bespectacled, constantly updating, perpetually connected, unable to understand why her father refuses to want more. The generational clash is not about technology versus tradition. It is about two fundamentally different relationships with desire.",
      "The play\u2019s philosophical DNA is eclectic. Shah and Manek drew from Japanese ikigai \u2014 the concept of a reason for being. From Sufism \u2014 the tradition that locates the divine in the act of surrender. From Zen Buddhism \u2014 the discipline of finding completeness in emptiness. \u2018We had initially wanted to make a play about a Zen master,\u2019 Shah told The Hindu\u2019s Vikram Phukan, \u2018but felt that might be alienating to Gujarati audiences.\u2019 So they made a play about a crow instead.",
      "Phukan, in his review, described Kaagdo as an \u2018existential parable\u2019 that was \u2018not didactic in its approach.\u2019 This is the key distinction. The play does not argue that happiness is good and ambition is bad. It does not preach simplicity. It presents a man who is happy and a world that cannot tolerate it, and leaves the audience to decide which side of the courtroom they are sitting on.",
      "Shah said something in that interview that deserves to be the play\u2019s epitaph: \u2018Even sadness is a tradition of happiness, which ultimately can be found within us.\u2019 It is a line that sounds like a fortune cookie until you sit with it. Sadness is a tradition of happiness. The capacity to feel sorrow is itself evidence that joy exists. The two are not opposites. They are the same substance, experienced from different angles. Kaagdo knows this. The court does not.",
    ],
    inlineImages: [
      { afterParagraph: 2, src: "/images/productions/kaagdo/DSC02998.JPG", alt: "Jay Upadhyay as Kaagdo \u2014 the happy man surrounded by floating smileys" },
      { afterParagraph: 4, src: "/images/productions/kaagdo/DSC03000.JPG", alt: "The courtroom confrontation \u2014 Unnati Gala interrogates her father\u2019s happiness" },
    ],
  },
  {
    slug: "jal-jal-mare-patang-manilal-dwivedi",
    title: "Jal Jal Mare Patang: The Philosopher Who Burned Too Bright for Forty Years",
    category: "Heritage",
    excerpt: "Married at fourteen. India\u2019s first women\u2019s magazine editor. Invited to the Parliament of World Religions before Vivekananda. Dead at forty. The story of Manilal Dwivedi, the man Gujarati literature is named after.",
    image: "/images/productions/jal-jal-mare-patang/Jal Jal Mare Patang - Prithvi (1).jpg",
    date: "2009-04-15",
    body: [
      "The title translates as \u2018the kite burns as it flies.\u2019 It is a metaphor for Manilal Nabhubhai Dwivedi, who was born in Nadiad, Gujarat on 26 September 1858 and died in the same town on 1 October 1898, writing at his desk. He was forty years old. In those forty years, he wrote the first tragic hero in Gujarati literature, founded India\u2019s first women\u2019s magazine, introduced Western philosophy to an entire region of India, and produced a body of work so significant that the era of Gujarati literature from 1885 to 1905 is named after him: the Mani-Govardhan Era.",
      "The facts of his life read like a novel that no one would believe. He was married at fourteen to a four-year-old girl named Mahalaxmi. He earned a BA from Elphinstone College in history and politics, then became a professor of Sanskrit at Samaldas College in Bhavnagar. He founded the magazine Priyamvada in 1885 \u2014 dedicated to women\u2019s education and empowerment at a time when the idea itself was radical \u2014 and later renamed it Sudarshan, publishing it until his death.",
      "In 1893, he was invited to present a paper at the first Parliament of World Religions in Chicago \u2014 the same event where Vivekananda delivered his famous speech beginning \u2018Sisters and brothers of America.\u2019 Dwivedi could not afford to attend. His paper on Hinduism was read by Virchand Gandhi on his behalf. His book Raja Yoga, written in English in 1885, was praised by the orientalist Sir Edwin Arnold and later read by Mahatma Gandhi while imprisoned in South Africa in 1908.",
      "Narmad, the founder of modern Gujarati literature, considered Dwivedi his intellectual heir. The poet-prince Kalapi of Lathi was his devoted follower. His play Kanta (1882) created the first tragic hero in Gujarati drama, fusing Sanskrit dramatic conventions with Shakespearean tragedy. His autobiography Atmavrittanta \u2014 written around 1886 and published posthumously only in 1979 \u2014 has been compared to Rousseau\u2019s Confessions and Havelock Ellis\u2019s My Life for its unflinching candour about his intellectual, spiritual, and personal struggles.",
      "Manoj Shah spent seven years researching Dwivedi\u2019s life before staging Jal Jal Mare Patang. The script, written by Mihir Bhuta, was drawn from the autobiography and other sources. The production premiered on 28 February 2009 at NCPA and later performed at Prithvi Theatre. It received an A-certificate from the Maharashtra Censor Board of Theatres for its frank depiction of Manilal\u2019s personal life \u2014 a life marked by contradictions: the advocate of women\u2019s empowerment whose own marriage collapsed, the philosopher of spiritual discipline whose body was ravaged by disease.",
      "The visual language of the production was shaped by Atul Dodiya, one of India\u2019s foremost contemporary artists, who created the backdrop paintings. This was the third collaboration between Ideas Unlimited and a major painter \u2014 following Bhupen Khakhar\u2019s work on Master Phoolmani and Ghulam Mohammed Sheikh\u2019s on Mareez. Dodiya would later paint the black-and-white backdrops for Mohan No Masalo.",
      "Dwivedi remains one of those figures whose influence far exceeds his fame. He is the man Gujarati literature is named after, yet most Gujaratis could not describe his life. His philosophical work arguing the superiority of Advaita Vedanta provoked years of controversy. His seven-year intellectual dispute with Ramanbhai Neelkanth of the Prarthana Samaj has been called unparalleled in Gujarat\u2019s history of reflective literature. He wrote 24 volumes of original work in Gujarati, Sanskrit, and English before the age of forty.",
      "The kite burned as it flew. Jal Jal Mare Patang does not mourn this. It traces the arc \u2014 the full, blazing, contradictory arc of a man who introduced a civilisation to itself through the medium of another civilisation\u2019s philosophy, and who died, as he lived, in the middle of a sentence.",
    ],
    inlineImages: [
      { afterParagraph: 1, src: "/images/productions/jal-jal-mare-patang/Jal Jal Mare Patang - Prithvi (1).jpg", alt: "Vedish Jhaveri as the young Manilal Dwivedi in Jal Jal Mare Patang" },
      { afterParagraph: 4, src: "/images/productions/jal-jal-mare-patang/JJMP NCPA (17).JPG", alt: "The ensemble of Jal Jal Mare Patang at NCPA \u2014 19th-century Gujarat on stage" },
      { afterParagraph: 6, src: "/images/productions/jal-jal-mare-patang/JJMP NCPA (6).JPG", alt: "A scene from Jal Jal Mare Patang at NCPA" },
    ],
  },
  {
    slug: "hu-chandrakant-bakshi-gujarati-writer",
    title: "Hu Chandrakant Bakshi: 178 Books, One Banned Story, and Zero Apologies",
    category: "Heritage",
    excerpt: "He authored 178 books, served as Sheriff of Mumbai, got arrested for a short story, defied Bal Thackeray, and never apologised to anyone. The play that brings Gujarati literature\u2019s most controversial writer to the stage.",
    image: "/images/productions/hu-chandrakant-bakshi/Photos (3).jpg",
    date: "2013-07-15",
    body: [
      "Chandrakant Bakshi was born in Palanpur, Gujarat in 1932 into a Jain family. He studied at St. Xavier\u2019s College, Calcutta, earned degrees in law and history, and worked twelve years in the textile business before becoming a professor of history at Mithibai College, Mumbai. He published his first stories while still in Calcutta. By the time he died of a heart attack in Ahmedabad in 2006, he had written 26 novels, 15 short story collections, 17 books on history and culture, 6 on politics, 8 travelogues, and an autobiography called Bakshinama that remains one of the most extraordinary documents in Gujarati literature. One hundred and seventy-eight books in total. No Gujarati writer before or since has matched that output.",
      "His writing style was deliberately provocative. He wrote Gujarati infused with Urdu, Hindi, and English words \u2014 a polyglot prose that mirrored the way educated Indians actually think. His characters were existentialist figures: suffering, frustrated, surviving. His most famous novel, Paralysis (1967), about a professor remembering his life from a hospital bed while half his body is paralysed, was translated into Marathi, English, and Russian. His short story \u2018Kutti\u2019 was banned by the Gujarat government and an arrest warrant was issued against him. Bakshi fought the case alone. The government eventually withdrew all charges.",
      "He was also, by every account, an extraordinary egoist. He believed he was the greatest Gujarati writer alive and said so publicly, repeatedly, and without a trace of irony. His newspaper columns were sharp and brutal. When Bal Thackeray\u2019s party demanded an apology for something he wrote, he refused. He never apologised to anyone for anything. He served as Sheriff of Mumbai in 1999 \u2014 a ceremonial position that seemed designed for a man who already believed the city belonged to him. His readers loved him for all of it.",
      "When Bakshi died in 2006, his column stopped but his presence did not. His books continued to sell. His sentences continued to be quoted at dinner parties and literary festivals. And then, in 2013, Ideas Unlimited brought him back to the one place he had never occupied: a stage.",
      "Shishir Ramavat \u2014 a Gujarati journalist who has worked at Chitralekha and Mid-Day and currently serves as editor at Gujarat Samachar \u2014 wrote the play drawing on Bakshinama and Bakshi\u2019s other writings. The result is not a conventional biography. It is a monologue delivered by a man who is simultaneously performing his life and daring the audience to judge him. Manoj Shah\u2019s staging uses a single prop throughout: a ladder, which Bakshi climbs, perches on, and descends. The metaphor is obvious and perfect. This is a man who was always climbing, always looking down.",
      "The play premiered on 15 June 2013 at Prithvi Theatre, Mumbai, and has since been performed at NCPA, Scrapyard Theatre in Ahmedabad, and venues across India. CreativeYatra called it \u2018a riveting drama on the life of the audacious Gujarati author,\u2019 praising the lead performance as \u2018cautious yet fearless\u2019 \u2014 a description that could apply to Bakshi\u2019s own writing. Pratik Gandhi, who plays Bakshi, brings an intensity to the role that does not perform for the audience but confronts them, capturing a man of contradictions: brilliant and petty, generous and cruel, vain and fearless, often in the same breath.",
      "What the play gets right \u2014 what a conventional biography would miss \u2014 is the relationship between Bakshi and his readers. He wrote for them. He fought for them. He insulted everyone else, but to his readers he was unfailingly devoted. The play captures this mutual obsession: a writer who loved his audience and an audience that loved him back, not despite his flaws but because of the unapologetic force with which he lived them. Hu Chandrakant Bakshi does not ask the audience to like him. It asks them to reckon with him. Which is, of course, exactly what Bakshi himself always demanded.",
    ],
    inlineImages: [
      { afterParagraph: 1, src: "/images/productions/hu-chandrakant-bakshi/Photos (1).jpeg", alt: "Pratik Gandhi as Chandrakant Bakshi \u2014 crouching on the bare Prithvi Theatre stage" },
      { afterParagraph: 3, src: "/images/productions/hu-chandrakant-bakshi/Photos (5).jpg", alt: "Bakshi on stage \u2014 the writer\u2019s contradictions on display" },
      { afterParagraph: 5, src: "/images/productions/hu-chandrakant-bakshi/Photos (7).jpg", alt: "The solo performance of Hu Chandrakant Bakshi" },
    ],
  },
  {
    slug: "dr-anandibai-like-comment-share",
    title: "Dr. Anandibai: The Woman Who Sailed to America in 1886 and the Play That Asked If Anything Has Changed",
    category: "Heritage",
    excerpt: "India\u2019s first female doctor died at twenty-two. A hundred and thirty years later, Manasi Joshi stands alone on a bare stage and asks: has anything changed for Indian women?",
    image: "/images/productions/dr-anandibai/Anandibai 4.JPG",
    date: "2018-01-20",
    body: [
      "On 31 March 1865, a girl named Anandi was born in Kalyan, Maharashtra. She was married at nine to Gopalrao Joshi, a man nearly twice her age, who — unusually for the time — believed in women\u2019s education. When their infant son died due to lack of medical care, Gopalrao wrote a letter to Royal Wilder, a missionary, asking for help sending Anandi to America to study medicine. It was 1880. The idea was preposterous.",
      "Six years later, Anandibai Joshi sailed to Philadelphia and enrolled at the Woman\u2019s Medical College of Pennsylvania. She endured the American winter, the strangeness of a foreign country, and the tuberculosis that was already consuming her body. In 1886, she earned her MD — the first Indian woman to do so. She returned to India as physician-in-charge at the Albert Edward Hospital in Kolhapur. On 26 February 1887, she died. She was twenty-two years old.",
      "This is the story that Geeta Manek chose to dramatise for Ideas Unlimited. But the play she wrote — Dr. Anandibai Joshi: Like, Comment, Share — is not a conventional biography. It is structured around a provocation: the language of social media. Like. Comment. Share. The three gestures that define how modern women present themselves to the world, seek validation, and measure their worth. Manek uses this framework to ask whether the forces that constrained Anandibai in the 1880s — the need for male approval, the reduction of women to domestic roles, the punishment of ambition — have truly disappeared, or merely migrated to new platforms.",
      "The play was Manoj Shah\u2019s first production to feature a woman in the solo role. For nearly two decades, his one-person plays had been performed by men — Pratik Gandhi, Satchit Puranik, Chirag Vohra. When he decided to break this pattern, the choice of subject was deliberate: not just any woman, but the woman who broke the most fundamental pattern of all.",
      "Manasi Prabhakar Joshi performs the seventy-five-minute monologue alone on a bare stage. No props. No set. Just Kabir Thakore\u2019s spatial design and Hemant Joshi\u2019s lighting, carving a world out of darkness. Joshi — a META award winner who has performed over 550 shows of Sangeet Devbabhali, appeared in Hotel Mumbai alongside Dev Patel and Anupam Kher, and voiced Phineas in the Hindi dub of Phineas & Ferb — brings a musical theatre performer\u2019s stamina and a classical singer\u2019s breath control to a role that demands both.",
      "The play premiered on 2 December 2017 at NCPA\u2019s CentreStage Festival. DNA India covered the opening, noting the play\u2019s unusual structure and its resonance with contemporary debates about women\u2019s freedom. It was later staged in Hindi and Marathi — the same story told in three languages, each version revealing different emotional textures, just as Ideas Unlimited had done with Mohan No Masalo two years earlier.",
      "The highest recognition came in 2018, when the play was selected for the 8th Theatre Olympics — the first time India hosted the event, with performances across seventeen cities. Theatre critic Deepa Gahlot cited it among the ten most socially relevant theatre productions in India, praising both the power of the story and Manasi Joshi\u2019s performance.",
      "Dr. Anandibai Joshi lived twenty-two years. In that time, she crossed an ocean, earned a degree that no Indian woman had earned before, and returned home to serve. She did not live to see the impact of what she had done. The play does not pretend otherwise. It does not give her a triumphant ending. It gives her something rarer: a stage, a voice, and an audience one hundred and thirty years later that is still grappling with the questions her life raised.",
    ],
    inlineImages: [
      { afterParagraph: 1, src: "/images/productions/dr-anandibai/Anandi 01.jpeg", alt: "Manasi Joshi as Dr. Anandibai \u2014 seated on stage with traditional textile backdrop" },
      { afterParagraph: 4, src: "/images/productions/dr-anandibai/Anandibai 8.JPG", alt: "Manasi Joshi performing the 75-minute solo monologue" },
      { afterParagraph: 6, src: "/images/productions/dr-anandibai/Anandibai 1.JPG", alt: "Dr. Anandibai: Like, Comment, Share \u2014 dramatic lighting against darkness" },
    ],
  },
  {
    slug: "bombay-flower-ruttie-jinnah-parsi-theatre",
    title: "Bombay Flower: The Parsi Socialite Who Married the Man Who Divided India",
    category: "Behind the Scenes",
    excerpt: "At eighteen, Ruttie Petit defied her family, her faith, and Bombay society to marry Muhammad Ali Jinnah. By twenty-nine, she was dead. Ideas Unlimited\u2019s Gujarati play recovers her story.",
    image: "/images/productions/bombay-flower/Copy of 26MAR23_BombayFlower_TET_139.JPG",
    date: "2023-04-15",
    body: [
      "Sarojini Naidu called her the \u2018Flower of Bombay.\u2019 She was born Rattanbai Petit in 1900, daughter of Sir Dinshaw Petit, second baronet \u2014 one of the wealthiest and most prominent Parsi families in colonial India. She grew up in a mansion, attended by servants, educated in the finest traditions of an elite Bombay household. At sixteen, she met Muhammad Ali Jinnah at a dinner party. He was forty, a brilliant barrister, the most charismatic Muslim leader in Indian politics, and twenty-four years her senior. Two years later, on her eighteenth birthday, she married him.",
      "The marriage outraged everyone. Sir Dinshaw sued Jinnah under the Guardians and Wards Act to prevent it \u2014 and lost, because Ruttie had turned eighteen. She converted to Islam, took the name Maryam Jinnah, and walked out of the Petit household forever. Her parents performed an uthamna \u2014 a Parsi death ritual \u2014 for their living daughter. She was dead to them.",
      "What followed is one of the most tragic personal stories in Indian political history. Ruttie\u2019s exuberance and warmth clashed with Jinnah\u2019s emotional austerity and consuming political ambition. She turned to theosophy, opium, alcohol. She wandered alone through Europe. She came back. She left again. On February 20, 1929, she died in Bombay at twenty-nine. Jinnah, the man who would go on to create Pakistan, wept openly at her funeral. It was one of the only times anyone saw him weep.",
      "This is the story that Geeta Manek dramatised for Ideas Unlimited as Bombay Flower. The script was drawn from Sheela Reddy\u2019s Mr and Mrs Jinnah: The Marriage That Shook India and Rajendra Mohan Bhatnagar\u2019s Ruttie Jinnah: Ek Alag Drashtikon. It took four years to develop. Manoj Shah initially envisioned a one-woman play, but the story demanded more voices. \u201CWhen we started working on it, something was amiss,\u201D he told The Indian Express. \u201CSo we brought in Jinnah. Still unconvinced, we had to add a few more characters \u2014 Ruttie\u2019s parents, Jinnah\u2019s sister, and Kanji Dwarkadas.\u201D",
      "The play premiered to a full house at the Experimental Theatre, NCPA on March 26, 2023 \u2014 an NCPA co-production. Bhamini Oza Gandhi played Ruttie with what the Parsiana magazine\u2019s Farrokh Jijina called a performance of \u2018highs and lows\u2019 that captured both the exuberance and the disintegration. Vishal Shah brought Jinnah to life \u2014 charming, remote, obsessed with politics. Naman Sheth played Kanji Dwarkadas, Rishabh Kamdar was Sir Dinshaw, and Purvi Desai took the dual roles of Lady Dinbai and Fatima Jinnah.",
      "The Parsiana review noted one of the play\u2019s most affecting moments: a telephone scene where Ruttie desperately tries to reach Jinnah through a telephone operator on her birthday. He is not there. He is never there. The monologue \u2014 played against an antique telephone, Bhamini\u2019s face shifting from hope to bewilderment to quiet devastation \u2014 distills the entire marriage into three minutes.",
      "Bombay Flower is dedicated to Parsi theatre, and this is not a casual gesture. Manoj Shah\u2019s research for Master Phoolmani in 1999 \u2014 a play about the Bhangwadi tradition of Gujarati theatre \u2014 led him to a discovery that shaped his understanding of Indian stage history: Parsis were the pioneers of Gujarati theatre. They were even pioneers of Urdu theatre. \u201CThe reason behind Bombay Flower being dedicated to Parsi theatre,\u201D Shah told Parsiana, \u201Cis to recall these contributions so our younger generation respects and learns from this culture.\u201D",
      "The play asks a question that Shah considers urgent in 2023: why would an intelligent, sensitive young woman from a privileged and respectable background choose to elope with a man from a completely different faith and sensibility? The programme notes frame it as an attempt to understand \u2018the elements that make even educated and empowered girls today take such decisions.\u2019 It is a delicate framing \u2014 neither endorsement nor condemnation, but examination.",
      "Beyond the personal story, Bombay Flower paints a portrait of a nation on the brink. Poet Iqbal\u2019s ideological seeds germinate in Jinnah\u2019s mind. The demand for Pakistan takes shape. Ruttie\u2019s personal disintegration mirrors India\u2019s impending fracture. The woman who crossed every boundary \u2014 family, faith, community \u2014 married the man who would draw the most consequential boundary of all.",
      "Ruttie Petit lived twenty-nine years. She has been the subject of at least three books, but until Bombay Flower, she had never been staged. The play does not claim to know her \u2014 some fiction is mixed with fact, as Shah acknowledged about the uthamna scene set at Dadysett Agiary. What it does is return her to the place she belonged: a stage in Bombay, where a Gujarati play named after her can bloom for two hours before the lights come down.",
    ],
    inlineImages: [
      { afterParagraph: 2, src: "/images/productions/bombay-flower/26MAR23_BombayFlower_TET_64.JPG", alt: "Bhamini Oza Gandhi as Ruttie Petit \u2014 the exuberant Bombay Flower" },
      { afterParagraph: 5, src: "/images/productions/bombay-flower/Copy of 26MAR23_BombayFlower_TET_139.JPG", alt: "The telephone scene \u2014 Ruttie tries to reach Jinnah on her birthday" },
      { afterParagraph: 7, src: "/images/productions/bombay-flower/Copy of 26MAR23_BombayFlower_TET_173.JPG", alt: "Ruttie and Jinnah \u2014 the marriage that shook India" },
    ],
  },
  {
    slug: "bhavprapanch-first-allegorical-novel-stage",
    title: "Bhav Prapanch: Staging India\u2019s First Allegorical Novel",
    category: "Heritage",
    excerpt: "A thousand years before Bunyan\u2019s Pilgrim\u2019s Progress, a Jain monk named Siddharshi wrote the world\u2019s first allegorical novel. Ideas Unlimited brought its 16,000 verses to life on stage.",
    image: "/images/productions/bhavprapanch/IT5A7129.JPG",
    date: "2014-06-15",
    body: [
      "In the 10th century, a Jain monk named Siddharshi Gani composed a work in Sanskrit that the German Indologist Hermann Jacobi would later call the first allegorical novel in Indian literature. The Upamitibhavaprapancha Katha \u2014 literally, the story of worldly illusion through analogy \u2014 runs to 16,000 verses in anushtup metre, woven into a champu format that alternates between prose and poetry. It predates John Bunyan\u2019s The Pilgrim\u2019s Progress by seven centuries and Guillaume de Deguileville\u2019s The Pilgrimage of the Life of Man by four.",
      "The text is not obscure to scholars. Peter Peterson\u2019s edition was published by the Asiatic Society in 1890. Analytical studies have appeared in Jain academic journals for over a century. But for most people \u2014 including most Jains \u2014 the Upamitibhavaprapancha Katha remains a title encountered only in footnotes. No one had attempted to stage it. The challenge was obvious: how do you dramatise 16,000 verses of allegorical philosophy?",
      "The answer came from an unlikely collaboration between a Jain Indologist and a theatre director. Dr. Jitendra B. Shah, Director of the L.D. Institute of Indology in Ahmedabad \u2014 a scholar who has authored twelve books, curated 10,000 manuscripts, and coordinated the Dalai Lama\u2019s meeting with Jain Acharyas \u2014 distilled Siddharshi\u2019s vast text into a theatrical concept. Prathang Dave and Raju Dave dramatised it into a script. Manoj Shah directed.",
      "The play follows Dramak, an ordinary soul living in a city called Adrishyamool Paryant \u2014 a name that translates roughly as \u2018invisible from root to end.\u2019 This city is the world as Jain philosophy understands it: a place governed by greed, attachment, illusion, and desire, where souls live bestial existences, accumulating karma through infinite cycles of birth and death, each time moving further from liberation.",
      "Dramak is not a villain. He is something more familiar and more unsettling: a person who wastes his time in futile efforts to protect possessions that will not last, relationships that will not survive death, and a body that is already decaying. He is, as the Gujarati synopsis puts it, a reflection of our everyday lives \u2014 one we experience constantly but choose, out of ignorance and attachment, to ignore.",
      "Against this stands the Maharaja\u2019s royal temple \u2014 maintained by servants, attendants, and ministers who embody dharma, renunciation, compassion, and mercy. They are always ready to guide souls toward liberation. Their hands are always extended. The question the play asks is not whether help exists, but whether we are willing to take it.",
      "The staging was monumental. Kabir Thakore \u2014 the Ahmedabad architect who built Scrapyard Theatre in his own courtyard \u2014 designed sets that moved between the squalor of Dramak\u2019s worldly existence and the luminous grandeur of the Maharaja\u2019s temple. Kanhaiya composed the music. Rajiv Bhatt designed costumes that ranged from the ragged burlap of the trapped soul to the pristine white of the Jain monk. The cast included Dharmendra Gohil, Vimal Upadhyay, Jay Upadhyay, Hemang Vyas, and Manoj Shah himself.",
      "What makes Bhav Prapanch distinctive in the Ideas Unlimited catalogue is its ambition. This is not biography or social commentary or literary adaptation. This is metaphysics staged as theatre \u2014 an attempt to make the abstract mechanics of karma, rebirth, and liberation visible and visceral. The masked figures representing worldly temptation, the tormented soul crawling across the stage, the serene monk standing in golden light while chaos swirls around him \u2014 these are images that work on an audience the way the original text was meant to work on a reader: not through argument, but through experience.",
      "Siddharshi wrote for monks and scholars. Manoj Shah staged it for everyone. The Gujarati language, the theatrical form, the physical immediacy of live performance \u2014 these translate Jain philosophical concepts into something an audience can feel in their body, not just process in their mind. You do not need to know what \u2018anushtup metre\u2019 means to understand a man clutching at possessions that are already slipping through his fingers.",
      "The play\u2019s tagline, taken from the poster, reads: the end of sorrow is the beginning of peaceful happiness. It is a Jain idea, but it is also a theatrical promise. Bhav Prapanch does not lecture. It shows you the sorrow first \u2014 in all its bewildering, masked, terrifying detail \u2014 and then it shows you the way out. The monk in white. The temple that was always there. The hand that was always extended.",
    ],
    inlineImages: [
      { afterParagraph: 2, src: "/images/productions/bhavprapanch/IT5A7190.JPG", alt: "Dramak in the city of illusion \u2014 the tormented soul in Bhav Prapanch" },
      { afterParagraph: 5, src: "/images/productions/bhavprapanch/IT5A7476.JPG", alt: "Masked figures of worldly temptation surround the soul in Bhav Prapanch" },
      { afterParagraph: 7, src: "/images/productions/bhavprapanch/IT5A7905.JPG", alt: "The Jain monk in white \u2014 the path to liberation in Bhav Prapanch" },
      { afterParagraph: 9, src: "/images/productions/bhavprapanch/IT5A8141.JPG", alt: "The full ensemble of Bhav Prapanch \u2014 flower petals and spiritual awakening" },
    ],
  },
  {
    slug: "bhamasha-jain-warrior-funded-freedom",
    title: "Bhamasha: The Jain Warrior Who Funded Maharana Pratap\u2019s Last Stand",
    category: "Heritage",
    excerpt: "Everyone knows Maharana Pratap. Almost no one knows the man who made his resistance possible. Ideas Unlimited\u2019s Hindi historical drama recovers the extraordinary story of Bhamashah.",
    image: "/images/productions/bhamasha/Bhamasha (2).JPG",
    date: "2013-02-15",
    body: [
      "There is a moment in the history of Mewar that school textbooks mention in passing, if at all. After the Battle of Haldighati in 1576, Maharana Pratap\u2019s army was shattered. His treasury was empty. His family lived in the hills, eating bread made from grass seeds. The Mughal empire, under Akbar, controlled everything. Pratap was ready to surrender. And then a man walked into his camp carrying twenty lakh gold coins and two-and-a-half crore silver rupees \u2014 enough to fund an army for twelve years. That man was Bhamashah.",
      "Born in 1547 into the Kavdia gotra of the Oswal Vaishya community, Bhamashah was a Jain Shravak \u2014 a layperson committed to the principles of non-violence, truthfulness, and right conduct. His father, Bharmal, had served as fort commander of Ranthambore. Bhamashah himself rose to become Diwan \u2014 Prime Minister \u2014 of Mewar under Maharana Pratap. He was responsible for the state\u2019s economy, military strategy, and administration. He was, in other words, not merely a donor. He was the architect of Mewar\u2019s survival.",
      "The play Bhamasha, staged by Ideas Unlimited at the Tata Theatre, NCPA on Republic Day 2013, sets out to recover this man from the footnotes. The story was conceived by Dr. Bipin Doshi, a Jain scholar who recognised that Bhamashah\u2019s significance extended far beyond a single act of generosity. Mihir Bhuta dramatised the narrative, building a structure that moves between the Mughal courts, the Rajput battlefields, and the Jain merchant\u2019s inner world of conscience and calculation.",
      "Dayashankar Pandey \u2014 known to millions from Taarak Mehta Ka Ooltah Chashmah and to cinephiles from Lagaan and Swades \u2014 took on the title role. He spent weeks working on the Rajasthani dialect, inhabiting a character who is simultaneously a shrewd businessman, a fearless warrior, and a devout Jain. \u201CTheatre is a place where we can experiment, grow, learn and improvise,\u201D Pandey said of the experience. \u201CAll actors should experience this magic once.\u201D",
      "The production\u2019s most distinctive element was its music. Chugge Khan, the Rajasthani Manganiar folk musician whose work has since appeared on Coke Studio and international festival stages, led a live ensemble of traditional musicians. The Marwari folk songs they performed were not incidental music. They were the emotional architecture of the play \u2014 the sound of a desert civilisation fighting for its existence.",
      "Om Puri, one of Indian cinema\u2019s most commanding voices, provided the recorded narration. Yashpal Sharma, the actor best known for Lagaan and Gangaajal, contributed voice-over work. Kabir Thakore, the Ahmedabad-based architect and theatre veteran who serves as convener of Rangmandal, designed sets that evoked Mughal-era palaces and Rajput fortresses with an economy that left room for the actors and music to breathe.",
      "The historical Bhamashah\u2019s story does not end with the famous donation. With the wealth he provided, Maharana Pratap rebuilt his army and launched the Battle of Dewair in 1582, recovering western Mewar including Kumbhalgarh, Udaipur, and Gogunda. Thirty-six thousand Mughal soldiers reportedly surrendered. Bhamashah served as treasurer of Mewar until his death in 1600. His descendants served as Prime Ministers of Udaipur for generations. The Indian government issued a postage stamp in his honour in 2000.",
      "What makes Bhamashah\u2019s story particularly resonant \u2014 and what the play foregrounds \u2014 is the question of what it means to be a Jain Shravak in a time of war. The Jain commitment to ahimsa is often misread, even within the community, as passive non-resistance. Bhamashah\u2019s life argues otherwise. He fought in battles. He raided Mughal camps. He gave everything he had to defend his land. His ahimsa was not the absence of action. It was the refusal to let injustice stand unchallenged.",
      "Ideas Unlimited had built its reputation on Gujarati biographical dramas \u2014 Mareez, Apurva Avsar, Jal Jal Mare Patang. Bhamasha was the company\u2019s first major Hindi-language production, and Manoj Shah chose the biggest stage available: the thousand-seat Tata Theatre at NCPA, on the most symbolic date in the Indian calendar. The ambition was deliberate. This was not a community play for a Jain gathering. This was Indian history, staged for an Indian audience.",
      "The play\u2019s success led to a 2017 film adaptation, with Dayashankar Pandey and Dharmendra Gohil reprising their roles and Manoj Shah appearing as a Sadhu. The film, rated 7.6 on IMDb and available on Zee5, brought the story to an even wider audience. But the stage version, with its live Manganiar orchestra and the electric proximity of the theatre, remains the definitive telling.",
      "Bhamashah is remembered today primarily as a philanthropist \u2014 the man who gave. But the play insists he was something more: the man who understood that freedom has a cost, and that paying it is not charity but duty. In a culture that venerates the king on the battlefield, Bhamasha asks us to look behind him \u2014 at the merchant, the strategist, the Jain who believed that protecting his people was the highest form of non-violence.",
    ],
    inlineImages: [
      { afterParagraph: 2, src: "/images/productions/bhamasha/Bhamasha (14).JPG", alt: "The full ensemble of Bhamasha on stage at NCPA \u2014 battle scene with Mughal-era sets" },
      { afterParagraph: 5, src: "/images/productions/bhamasha/Bhamasha (10).JPG", alt: "A scene from Bhamasha \u2014 courtly encounter in the Mewar palace" },
      { afterParagraph: 8, src: "/images/productions/bhamasha/Bhamasha (13).JPG", alt: "Intimate moment in Bhamasha \u2014 the personal cost of war" },
    ],
  },
  {
    slug: "adbhut-every-brilliant-thing-gujarati",
    title: "Adbhut: How a British Play About Depression Found Its Truest Voice in Gujarati",
    category: "Behind the Scenes",
    excerpt: "Duncan Macmillan and Jonny Donahoe\u2019s Every Brilliant Thing has been performed in over 80 countries. When Satchit Puranik adapted it into Gujarati and RJ Devaki stepped on stage, something shifted.",
    image: "/images/productions/adbhut/06MAR22_Adbhut_TET_208.JPG",
    date: "2022-04-10",
    body: [
      "In 2006, a British playwright named Duncan Macmillan wrote a fifteen-minute monologue called Sleeve Notes for actress Rosie Thomson. It was about a child who, after her mother\u2019s first suicide attempt, begins writing a list of every brilliant thing worth living for. Item 1: ice cream. The monologue caught the attention of director George Perrin, who encouraged Macmillan to expand it. In 2013, working with comedian and performer Jonny Donahoe, Macmillan turned it into a full-length solo show. They called it Every Brilliant Thing.",
      "It premiered at the Ludlow Fringe Festival, transferred to Edinburgh where it sold out three consecutive years, then moved to the Barrow Street Theatre off-Broadway and became an HBO special in 2016 filmed with Donahoe performing to a live audience. The play has since been staged in over 80 countries across six continents. In March 2026, Daniel Radcliffe opened in it on Broadway at the Hudson Theatre. Macmillan \u2014 who also co-adapted 1984 for the stage with Robert Icke, and wrote People, Places and Things (which won Denise Gough an Olivier Award) \u2014 had created something that transcended language and culture. Or so it seemed.",
      "It seemed that way because the play\u2019s power lies in its specificity. The particular texture of childhood memories. The precise shade of an adolescent\u2019s embarrassment. The exact weight of a parent\u2019s silence. These things are not universal. They are deeply, irreducibly local. A straight translation would carry the plot but lose the feeling. Which is why what Satchit Puranik did with Adbhut is not translation. It is transplantation.",
      "Puranik \u2014 an FTII graduate who edited Anand Gandhi\u2019s Ship of Theseus and handled casting for Chaitanya Tamhane\u2019s Court, two of the most acclaimed Indian independent films of the 2010s \u2014 rebuilt the list from scratch. Out went Saturday morning cartoons and school dances. In came Doordarshan evenings, the scent of rain on hot earth, the particular chaos of a Navratri garba, the taste of your grandmother\u2019s thepla. The architecture of Macmillan and Donahoe\u2019s play remained \u2014 the list, the audience participation, the arc from age seven to adulthood \u2014 but the soul became Gujarati.",
      "The format, for those unfamiliar with the original: before the show, audience members find numbered slips on their seats. Each slip contains an item from the list. When the performer calls out a number, the person holding that slip stands and reads it aloud. Other audience members are recruited on the spot to play the father, a school counsellor, a veterinarian, a love interest. The house lights stay on. There is no fourth wall to break because it was never built. Macmillan and Donahoe designed the play so that the thesis \u2014 we need each other, brilliant things are communal, speaking up matters \u2014 is embedded in the form itself.",
      "The question of who would perform the Gujarati version was answered by RJ Devaki. Born into what Ahmedabad calls its \u2018first family of Gujarati theatre,\u2019 Devaki Marks had already performed in over thirty plays, won the Best Actor award at Transmedia three years running, and built a parallel career as one of Gujarat\u2019s most recognised radio voices \u2014 the \u2018Golden Voice of Ahmedabad,\u2019 as the Governor titled her. She is not an obvious choice for a play about depression. She is warm, loud, physical, funny. Which is exactly why it works.",
      "Seventy-five minutes. A chair. A Daffy Duck sweatshirt. String lights. Nothing else. Devaki moves through the room \u2014 sitting next to a stranger, pulling an elderly uncle onto the stage, making a teenager read out a love letter \u2014 and the effect is disarming. You cannot maintain the safe distance of a spectator when the performer is looking you in the eye and asking you to name something brilliant.",
      "The play tracks its protagonist from age seven to womanhood. Her mother\u2019s depression is not dramatised or sensationalised. It is simply present, the way it is present in millions of Indian households \u2014 unspoken, misunderstood, covered up with explanations about tiredness or God\u2019s will. The girl\u2019s list is her private rebellion against this silence. Every item is an argument for being alive. The list grows past a thousand, past ten thousand, past a million. It never stops growing because the point is not to finish it.",
      "The music for Adbhut was composed by Amit Bhavsar, with songs by his son Siddharth Amit Bhavsar \u2014 the Ahmedabad-based composer known as Musicwaala whose work spans Gujarati cinema from Love Ni Bhavai to Sharato Lagu. The singers include Madhubanti Bagchi, whose voice most of India now knows from Aaj Ki Raat in Stree 2, and Yashika Sikka, who has recorded with A.R. Rahman. That this calibre of musical talent anchors a Gujarati theatre production says something about the gravitational pull of the material.",
      "Manoj Shah directed. Janam Shah produced. The NCPA co-produced and hosted the premiere in 2021. Since then, it has been performed at venues across Mumbai and Ahmedabad \u2014 Scrapyard, Prayogshala \u2014 and continues to draw full houses years later. Notably, an English-language Indian production of Every Brilliant Thing already existed, directed by Quasar Thakore Padamsee and performed by Vivek Madan, which was nominated at the META Awards. Adbhut is not competing with that version. It is doing something different: proving that the play\u2019s emotional core survives not just translation but cultural reinvention.",
      "Mental health remains one of Indian theatre\u2019s most underserved subjects. Bollywood has made films about it; stand-up comics joke about it; therapists post about it on Instagram. But the live, communal, inescapable experience of theatre does something none of those forms can: it puts you in a room with a hundred other people who are all feeling the same thing at the same time, and it says, you are not alone in this.",
      "Adbhut means \u2018wonder\u2019 in Gujarati. It is the right title. Not because the play is wonderful \u2014 though it is \u2014 but because it returns you to a state of wonder. The wonder of a seven-year-old who believes that a list of brilliant things can save her mother. The wonder of an audience that discovers, midway through a play about depression, that they are laughing. The wonder of realising, as the lights come up, that the person sitting next to you \u2014 a stranger you will never see again \u2014 is wiping their eyes too.",
    ],
    inlineImages: [
      { afterParagraph: 2, src: "/images/productions/adbhut/06MAR22_Adbhut_TET_83.JPG", alt: "RJ Devaki performing Adbhut — solo on stage" },
      { afterParagraph: 5, src: "/images/productions/adbhut/06MAR22_Adbhut_TET_336.JPG", alt: "Devaki interacting with audience members during Adbhut" },
      { afterParagraph: 8, src: "/images/productions/adbhut/06MAR22_Adbhut_TET_52.JPG", alt: "Audience participation during Adbhut — Devaki among the crowd" },
      { afterParagraph: 10, src: "/images/productions/adbhut/06MAR22_Adbhut_TET_208.JPG", alt: "Devaki seated cross-legged, arms outstretched — the wonder of Adbhut" },
    ],
  },
  {
    slug: "achalayatan-tagore-gujarati-theatre",
    title: "Achalayatan: When Tagore\u2019s Most Radical Play Spoke Gujarati",
    category: "Heritage",
    excerpt: "In 2008, Ideas Unlimited brought Rabindranath Tagore\u2019s fierce allegory of institutional rigidity to Kolkata\u2019s Tagore Festival \u2014 in Gujarati. The story of how a nearly-forgotten adaptation by Gandhian intellectuals found new life on stage.",
    image: "/images/productions/achalayatan/Achalayatan---4.jpg",
    date: "2008-10-15",
    body: [
      "Rabindranath Tagore wrote Achalayatan in 1911, a year before he would win the Nobel Prize for Literature. The title translates roughly as \u2018The Immovable Institution\u2019 \u2014 and the play is exactly about that: a system so petrified by its own rules that it has forgotten why those rules exist.",
      "The setting is an ashram, sealed off from the world. Its windows are shut. Its doors are locked. Even air from outside is considered contamination. The students recite scriptures they do not understand. The elders enforce rituals they cannot explain. Into this airless world steps Panchak, a young student who cannot bring himself to stop asking why.",
      "Panchak\u2019s crime is simple: he opens a window. Through it, he glimpses a world of untouchables living free, unencumbered lives outside the ashram walls. No rules, no hierarchy, no pretence of spiritual superiority \u2014 just people living. This encounter shatters his faith in the institution and sets him on a path toward a truth the ashram has spent centuries trying to wall out: that God does not live inside closed systems.",
      "The play is Tagore at his most allegorically fierce. It is a direct attack on the Hindu orthodoxy of his time \u2014 the rigid caste hierarchies, the empty ritualisms, the educational institutions that teach obedience rather than understanding. When it was first staged in Bengal, conservative audiences were outraged. Over a century later, the play\u2019s critique has only sharpened. Every country, every era, every institution builds its own Achalayatan.",
      "What makes the Ideas Unlimited production historically distinctive is the text itself. The Gujarati adaptation was not a modern commission. It was created decades earlier by a group of Gandhian intellectuals: Giridhar Kripalani adapted the Bengali original under the guidance of Kaka Kalelkar, with the process touched by figures like Mahadevbhai Desai and Swami Anand \u2014 men who moved between Tagore\u2019s Santiniketan and Gandhi\u2019s ashrams, bridging Bengal and Gujarat at the level of ideas.",
      "Mahadev Desai, Gandhi\u2019s personal secretary, was himself a prolific translator of Tagore into Gujarati, having rendered works like Chitrangada and Viday Abhishap in the 1920s. Kaka Kalelkar had studied at Santiniketan and maintained a lifelong connection to Tagore\u2019s vision of education. The Gujarati Achalayatan, then, was not merely a translation. It was a meeting point of two of India\u2019s great intellectual traditions \u2014 the Tagorean and the Gandhian \u2014 expressed in the language of Gujarat.",
      "Manoj Shah discovered this adaptation and recognised its power. \u201CAfter scanning all his work, I finally selected Achalayatan, because it is one of Tagore\u2019s best crafted plays,\u201D Shah wrote in his director\u2019s note. \u201CThe plot which revolves around issues like religion, education and society at large, has a very contemporary feel to it. I went through all the nuances of the play for six months and rehearsed with the actors for two months. In all it took me eight months to get the play ready for the stage.\u201D",
      "The choice carried weight beyond the literary. In 2008, staging a Gujarati-language production that excoriated religious orthodoxy required a particular kind of artistic nerve. As the theatre historian Ananda Lal noted in his survey of Tagore productions in Kolkata, Shah\u2019s choice \u201Cseemed quite brave, for Tagore is at his most scathing about rigid institutional practices in this play.\u201D Kolkata itself had not seen a major Achalayatan production in over a decade.",
      "The production premiered on 10 September 2008 at G. D. Birla Sabhagar in Kolkata, as part of a five-day Tagore Festival. It was the only Gujarati-language play in the programme \u2014 a Mumbaikar troupe performing a Bengali Nobel laureate\u2019s work in Gujarati, in the playwright\u2019s own city. The cast of over twenty performed in white and saffron against minimal sets, with Hussaini Dawavala\u2019s lighting design carving the ashram\u2019s claustrophobia out of darkness.",
      "The Gujarati press took notice. Shishir Ramavat, writing in Gujarat Samachar, described the production\u2019s emotional reach and the significance of bringing a Gujarati Tagore to Kolkata. Shah himself framed the play\u2019s tone not as opposition to systems but as self-discovery \u2014 a distinction that reveals something essential about his directorial philosophy. He does not stage polemics. He stages journeys.",
      "Achalayatan remains one of Tagore\u2019s most neglected major works. It is rarely staged in any language, let alone in Gujarati. Yet its core argument \u2014 that institutions calcify, that rules outlive their meaning, that the divine is not locked behind any door \u2014 is as urgent now as it was in 1911. In an era of hardening identities and shrinking intellectual spaces, Panchak\u2019s simple act of opening a window feels less like allegory and more like instruction.",
      "The production was a tribute, as the programme booklet stated, to India\u2019s first Nobel laureate. But it was also something rarer: proof that a great play does not belong to the language in which it was written. It belongs to whoever has the courage to perform it.",
    ],
    inlineImages: [
      { afterParagraph: 2, src: "/images/productions/achalayatan/Achalayatan-1.jpg", alt: "Ashram students in white — the rigid institution of Achalayatan" },
      { afterParagraph: 5, src: "/images/productions/achalayatan/Achalayatan---3.jpg", alt: "The Guruji arrives — a moment of liberation in Achalayatan" },
      { afterParagraph: 8, src: "/images/productions/achalayatan/Achalayatan---4.jpg", alt: "The walls of the ashram challenged — Achalayatan at G. D. Birla Sabhagar, Kolkata" },
      { afterParagraph: 10, src: "/images/productions/achalayatan/Achalayatan---2.jpg", alt: "Cast of Achalayatan on stage at the Tagore Festival, Kolkata 2008" },
    ],
  },
];

export function getAllPosts(): BlogPost[] {
  return BLOG_POSTS.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

export function getPostBySlug(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug);
}
